### ISSUE TITLE
[Bug]: Soft lock - Ranni's Barrier won't disappear

### ISSUE THREAD

**Issue by oCursed** [LukeYui/EldenRingSeamlessCoopRelease#96] opened 2022-06-11 11:45 UTC
### Discord Username

Cursed#7142

### Describe the issue in detail

Me and my friends (3 other people) got stuck at the Ranni tower even after talking to all the NPCs including Ranni, because of that we can't leave the tower or teleport anywhere (We can open the map but for any site of grace it says that we can't teleport for now, even at the Ranni Tower's Grace).

We tried to kill ourselves, restart the game, even playing in solo mode, the game is just soft locked, there is no other NPCs than Ranni and the only thing she says is "...".

Everyone has soft locked their game, nobody can leave the tower.
![travel](https://user-images.githubusercontent.com/107306476/173186414-9aa54f98-bdf2-473e-a43c-dae26b340e65.png)
![bug](https://user-images.githubusercontent.com/107306476/173186418-e39ce219-4a1a-462f-88ff-c1f355a935fb.png)

### Steps to recreate the bug

Go to Ranni's Tower with other people (i think 2 people is enough), talk to ranni and that's it.
Even if everyone talk to the 3 NPCs and Ranni (the final dialogue available is "..." with Ranni), the barrier is still there and nobody can leave the tower.

### Version

1.2.1 (Latest)

**Comment by LukeYui** [comment] 2022-06-11 13:39
Duplicate of #82

**Closed by LukeYui** 2022-06-11 13:39 UTC
Labels: bug
