### ISSUE TITLE
[Bug]: Witch-Hunter Jarren is missing and thus impossible to start Radahn festival

### ISSUE THREAD

**Issue by valkyrienyanko** [LukeYui/EldenRingSeamlessCoopRelease#424] opened 2022-07-11 20:27 UTC
### Discord Username

valk#9904

### Describe the issue in detail

I started a new game and someone else joined. As soon as they joined I received the eccentric armor set meaning they killed Witch-Hunter Jerren. Later in the game I found out that Witch-Hunter Jerren is no where to be found, he is not at the festival, or at witch bane ruins. I cannot revive him at the church of vows because it says I do not need absolution. This means there is literally no way to start the Radahn festival unless I suppose someone has not beaten Radahn in their world and I join their world and kill him together but I have still yet to find someone who hasn't beaten them in their world.

### Steps to recreate the bug

1. Create a new character / world
2. Let someone else join you who has beaten Radahn / killed Witch-Hunter Jerren
3. Go to Redmane Castle and notice Witch-Hunter Jerren is no where to be found

### Version

1.3.0 (Latest)

**Comment by Yoni0040** [comment] 2022-07-11 20:47
Duplicate of #55 

You can read @FallenWolf69 's comment for the solution.

**Closed** 2022-07-11 21:08 UTC
Labels: bug
