### ISSUE TITLE
[Bug]: Melina tries to take you to the roundtable hold every time you load into a world as a wanderer.

### ISSUE THREAD

**Issue by TheDevilsVirtue** [LukeYui/EldenRingSeamlessCoopRelease#74] opened 2022-06-10 21:34 UTC
### Discord Username

TheDevilsVirtue#2129

### Describe the issue in detail

Every time I try to join my friend or if he joins me, as soon as the player that isn't the host sits at the grace for the first time Melina attempts to take us to the roundtable hold. It goes through the dialogue all the same but when she grabs your hand it doesn't take you anywhere and your character sits back down and the menu for the grace pops back up. The bug is relatively harmless from what we've seen but after a while it gets very annoying.

### Steps to recreate the bug

I don't know if it happens for everyone but the most consistent way for us to do it is to sit at a grace after joining someone.

### Version

1.2.1 (Latest)

**Comment by LukeYui** [comment] 2022-06-10 21:50
Duplicate of #61

**Closed by LukeYui** 2022-06-10 21:50 UTC
Labels: bug, duplicate
