### ISSUE TITLE
[Bug]: Loss of lockon capibility during some boss fights

### ISSUE THREAD

**Issue by ArtoseAshwood** [LukeYui/EldenRingSeamlessCoopRelease#271] opened 2022-06-19 17:13 UTC
### Discord Username

Artose#4222

### Describe the issue in detail

While fighting Radaan both me and my guest would lose the ability to lock-on to the boss until the fight was restarted. We had to fight the boss solo because of this and this problem was not seen solo. I have not seen this bug anywhere else in the game.

### Steps to recreate the bug

Fight Radaan with a coop partner.

### Version

1.2.5 (Latest)

**Comment by ArtoseAshwood** [comment] 2022-06-20 20:55
We played a bit more and my fiend reported this happening again at the FULL-GROWN FALLINGSTAR BEAST boss fight at the top of Mt Gelmir.

**Comment by FlashbangGit** [comment] 2022-06-21 05:00
I have found this to be primarily related to being on your horse. My friend and I have had numerous boss fights that are normally fought from horseback (Tree Sentinels for example) will have players on horse lose the ability to lock on if the enemy. It generally happens to us between 1/2 and 3/4 boss life left. 

Since he is a ranged magic build, we started playing around with him not being on a horse, which causes him to never lose lock on. Furthermore, I have found that when it happens to me, I am sometimes able to lock onto my own horse instead of the boss.  I am the host for our games, however when he hosted the issue persisted with the same self-horse lock on happening for me.

**Comment by GavinRay97** [comment] 2022-06-21 16:26
Related to:

- https://github.com/LukeYui/EldenRingSeamlessCoopRelease/issues/293
- https://github.com/LukeYui/EldenRingSeamlessCoopRelease/issues/218
- https://github.com/LukeYui/EldenRingSeamlessCoopRelease/issues/177
- https://github.com/LukeYui/EldenRingSeamlessCoopRelease/issues/145

**Comment by loki2236** [comment] 2022-06-28 16:06
Duplicate of #21

**Closed** 2023-01-19 21:05 UTC
Labels: bug
