### ISSUE TITLE
[Bug]: After giving bell bearings, new shops do not appear

### ISSUE THREAD

**Issue by flintspike** [LukeYui/EldenRingSeamlessCoopRelease#405] opened 2022-07-07 10:31 UTC
### Discord Username

LAFFA#6522

### Describe the issue in detail

After acquiring the gostoc bell bearing and giving it to the twin husks, me and the host are both able to properly access the new shop.
However any subsequent bell bearing shops do not open. Me and the host both are unable to access the new shops despite being able to give the twin husk the bell bearings.

Typically this would unlock more shops but in this world it doesn't.

So we lose the bell bearing but dont get the shop.

The game was just me and one other person.

*edit* I just wanted to add that while playing this character solo, the issue persists, we have tried to access the shops alone but again, there is no effect. it seems that the bell bearings were eaten. I personally have tried using other characters as well but this issue persists. My friend has only the one character so I will see if he wants to try to make a new one to test it that way.

*edit 2* I also want to add that i do not mean to imply that gostocs bell bearing is the cause for the issue. I just found it strange that HIS worked but no other bell bearing has since then. 

### Steps to recreate the bug

Kill Gostoc

Give Gostoc bearing to twin husks.

Bell Bearing Shop 1 is accessible .

Get bell bearing from dead NPC.

Give to twin husks.

Lose bell bearing.

No new shop/items have become available.

### Version

1.2.5 (Latest)

**Comment by loki2236** [comment] 2022-07-08 13:57
Duplicate of #10

**Comment by loki2236** [comment] 2022-07-08 13:58
Workaround: Use Elden Ring debug tool to give yourself the bells again, also, don't give bell while playing as a wanderer, do it solo on your world. Shop don't sync at the time of this answer.

**Closed** 2022-07-10 23:06 UTC
Labels: bug, duplicate
