### ISSUE TITLE
[Bug]: Rennala freezes when host dies

### ISSUE THREAD

**Issue by NiharRao** [LukeYui/EldenRingSeamlessCoopRelease#468] opened 2023-01-22 20:02 UTC
### Describe the issue in detail

My friend and I were playing with the seamless coop 1.4.3 mod.
I was the host (friend joined my game). We noticed that every time I had died while my friend was alive, Rennala just stood there taking hits from my friend. (This was noticed during the second phase).

### Steps to recreate the bug

- Go to Rennala fight with 2 (or more?) players.
- Get to second phase.
- Host of the session dies by Rennala.
- Rennala is now frozen.

### Version

1.4.3 (Latest)

**Comment by NiharRao** [comment] 2023-01-22 20:03
I'm not sure if the same bug exists on the first phase of Rennala.

**Comment by A1steaksa** [comment] 2023-03-21 21:41
This is a duplicate of https://github.com/LukeYui/EldenRingSeamlessCoopRelease/issues/64

**Closed** 2023-04-30 20:37 UTC
Labels: bug, cannot recreate
