### ISSUE TITLE
[Bug]: Tiny Great Pot duplicated when I picked up an item

### ISSUE THREAD

**Issue by SelloutFred** [LukeYui/EldenRingSeamlessCoopRelease#197] opened 2022-06-15 06:18 UTC
### Discord Username

SelloutFred#2798

### Describe the issue in detail

Can't really say much, started a new game and picked up a rose plant item and it began SPAMMING that I had picked up a tiny great pot, I have over 900 in my inventory and it is just annoying nothing else though. Hope this helps! (Happened in the tutorial part of the start)

### Steps to recreate the bug

Just me, tutorial cave, right after the grace where there were plants

### Version

1.2.4 (Latest)

**Comment by TevildoBM** [comment] 2022-06-15 23:37
Same exact thing happened to me, but after picking up an item in Caelid. Started happening in this version as well. Only has happened once and I do not know what exactly triggers it.

**Comment by LukeYui** [comment] 2022-06-18 11:00
Duplicate of #71

**Closed by LukeYui** 2022-06-18 11:00 UTC
Labels: bug
