### ISSUE TITLE
[Bug]: Unable to lock on target

### ISSUE THREAD

**Issue by raphamdsid** [LukeYui/EldenRingSeamlessCoopRelease#218] opened 2022-06-16 16:07 UTC
### Discord Username

Raph#8415

### Describe the issue in detail

Sometimes bosses become untargetable or target focus vanish when you lock it.

### Steps to recreate the bug

Happened mostly on boss figfhts and I believe it happen more often when fighting on horseback.

### Version

1.2.4 (Latest)

**Comment by moldobmf** [comment] 2022-06-16 16:25
Can confirm this issue in 1.2.4. It happened pretty much 100% when trying to fight Tree Sentinel both when hosting and joining a session with a friend. It did also happen once on a random mob, but it was a one off then.

**Comment by LukeYui** [comment] 2022-06-16 18:20
Hi, I can't recreate this bug. Is there any steps you can take to do it consistently?

**Comment by SafetyTheFlameWolf** [comment] 2022-06-16 18:57
> Hi, I can't recreate this bug. Is there any steps you can take to do it consistently?

I've had this issue as well, however it seems to happen at random. I had it happen while fighting Tree Sentenial, Night Calvary, Erdtree/Putrid Avatar, and Radahn

**Comment by moldobmf** [comment] 2022-06-16 19:00
> Hi, I can't recreate this bug. Is there any steps you can take to do it consistently?

In our case we just made new characters, joined each other's session and went straight for Tree Sentinel right after. I was on controller, my friend was on M/K, and it happened more often to him, don't know if that might be relevant. We were also both on Win11.

**Comment by oCursed** [comment] 2022-06-16 21:10
I got the same issue during the Radhan fight with friends, it happens randomly, The target lock comes back after Radhan jump for his second phase.

**Comment by alizorro** [comment] 2022-06-20 23:32
Having this issue with almost every boss fight which is making it super hard to defeat as a sorcery character

**Comment by loki2236** [comment] 2022-06-28 15:39
Duplicate of #21

**Closed** 2023-01-19 21:06 UTC
Labels: bug
