### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by tanerkennedy** [LukeYui/EldenRingSeamlessCoopRelease#481] opened 2023-01-28 13:34 UTC
### Discord Username

annem de öyle diyordu#2224

### Describe the issue in detail

When me and my friend wants to teleport our first attempt always result with fail we have to vote 2 times and after our first attempt time we have to wait for failed notification and vote again.

### Steps to recreate the bug

me and my friend want to teleport and always first one result with fail

### Version

1.4.3 (Latest)

**Comment by HarleyDoom** [comment] 2023-01-28 16:17
Duplicate of #476

**Comment by LukeYui** [comment] 2023-01-28 22:52
As above, thank you

**Closed by LukeYui** 2023-01-28 22:52 UTC
Labels: bug
