### ISSUE TITLE
[Bug]: Grace-Melina-RoundTable

### ISSUE THREAD

**Issue by Kepfa** [LukeYui/EldenRingSeamlessCoopRelease#122] opened 2022-06-12 16:28 UTC
### Discord Username

Kepfa#4879

### Describe the issue in detail

for me and my friends melina wont stop popping up offering to take us to the roundtable even tho we already did it the first time she popped up. she either pops up everytime or every other time we hit the grace. yesterday two of us said yeah and two of us didnt and it brought the two who said yes to the roundtable, which i thought was weird bc i thought everyone had to say yes to be able to go to roundtable. i honestly dont know what version this has been happening since i dont pay attention but i think its 1.1.0.

### Steps to recreate the bug

when we hit the grace. 

### Version

1.1.0

**Comment by LukeYui** [comment] 2022-06-12 16:45
Duplicate of #23

**Closed by LukeYui** 2022-06-12 16:45 UTC
Labels: bug
