### ISSUE TITLE
[Bug]: Rennala got bugged after my cooperator died

### ISSUE THREAD

**Issue by Imaginescythe** [LukeYui/EldenRingSeamlessCoopRelease#353] opened 2022-06-27 16:06 UTC
### Describe the issue in detail

We were fighting Rennala on her 2.5 phase ( the one where she could summon spirits ), then my friend died, likely due to her Glintstone Stars attack. After the "... has fallen" message appeared, she straight up crashed and got stuck into this pose. After that, any stagger caused by my attack would stun her like normal, but then she would return back to this pose. I am not certain whether was it a vanilla game's bug or a Seamless bug, but still it should be worth checking out.
![unknown](https://user-images.githubusercontent.com/108289178/175983239-4dda2945-e19e-444c-b472-af8355653b55.png)
 

### Steps to recreate the bug

Get Renalla to her 2.5 phase, then let a cooperator be killed, she will then get glitched out and stuck in that pose.

### Version

1.2.5 (Latest)

**Comment by loki2236** [comment] 2022-06-28 17:11
Duplicate of #64

**Closed** 2022-07-06 21:22 UTC
Labels: bug
