### ISSUE TITLE
[Bug]: Lock on bug

### ISSUE THREAD

**Issue by insanemhelo** [LukeYui/EldenRingSeamlessCoopRelease#145] opened 2022-06-13 17:09 UTC
### Describe the issue in detail

While fighting a few enemies i have noticed that i am unable to lock on.  I do not know what is needed to make the bug happen.  I first thought it might of been cause the enemy had reset cause we pulled it to far.  I soon noticed that it wasnt just on the one that was reset.  Iv looked through the open bugs and seen ppl mention a horse lock on bug.  My lock on bug was happening off of my horse

### Steps to recreate the bug

Not sure.  Maybe pull enemy far from their spawn point and let them reset?

### Version

1.2.2

**Comment by Inverness** [comment] 2022-06-14 01:40
Going on and off the horse seems to fix this sometimes but it's often temporary.

**Comment by loki2236** [comment] 2022-06-28 16:08
Duplicate of #21

**Closed** 2023-01-19 21:06 UTC
Labels: bug
