### ISSUE TITLE
[Bug]: Game Crash after focusing deleted marker.

### ISSUE THREAD

**Issue by Inchinator** [LukeYui/EldenRingSeamlessCoopRelease#249] opened 2022-06-18 09:51 UTC
### Discord Username

Inchinator #3621

### Describe the issue in detail

When somebody in the lobby places a marker and another players happens to focus that marker at time of deletion, the player focusing will experience a game crash.
This happens when the marker gets deleted manually as well as through spam protection when u place more than 5 markers.
We tested this several times, it always happens.

We appreciate the work, still a great mod, keep going, ty <3

### Steps to recreate the bug

Focus the marker(in multiplayer of course) and have someone else remove it.

### Version

1.2.4 (Latest)

### Relevant Crash log

```shell
No Log.
```

**Comment by LukeYui** [comment] 2022-06-18 10:36
Duplicate of #94

**Closed by LukeYui** 2022-06-18 10:36 UTC
Labels: bug
