### ISSUE TITLE
[Bug]: Friends spawning out of bounds

### ISSUE THREAD

**Issue by longers2** [LukeYui/EldenRingSeamlessCoopRelease#186] opened 2022-06-15 01:07 UTC
### Describe the issue in detail

Updating to v1.2.4 introduced a bunch of bugs to our game. I'm playing with 2 other friends, and the game went much more smoothly on previous versions. We tried playing last night, and the bugs we encountered made it pretty unplayable.

When my friends joined my game, it would spawn them out of bounds and would instantly kill them. When they respawned, it would put them in whatever location they were in before joining my game. Then, anytime we tried quick traveling (either via the map or warping to the beginning of a dungeon after clearing it), at least 1 person would be stuck on the loading screen before their game closed. I'd have to close my world before they could rejoin. When they would rejoin, they'd spawn out of bounds again. Also, my friends weren't able to spend their runes on level ups while in my world. They had to separate from my world and spend their runes in their own world.

Again, these issues didn't occur on previous versions of the mod and just started occurring when we updated to v1.2.4

### Steps to recreate the bug

We (3 of us) were playing together for a bit. I think the bugs started occurring after we eared a dungeon. We tried to use the fast-travel point to return to the beginning of the dungeon (the one that spawns after killing the boss). One of my friends got stuck in a loading screen, and he wasn't able to return to my world after relaunching his game. I closed and reopened my world, and I think that's when they started spawning out of bounds.

### Version

1.2.4 (Latest)

**Comment by LukeYui** [comment] 2022-06-15 11:38
Hi, thanks for the report. I'll have the problem fixed for the next version.

In the mean time, you should be able to avoid this issue by having the host stand still while a wander joins, as the bug is caused by moving to a different map chunk whilst a player is loading in.

**Closed** 2022-06-19 21:32 UTC
Labels: bug, pending fix
