### ISSUE TITLE
[Bug]: lock on wont work

### ISSUE THREAD

**Issue by garntyblue** [LukeYui/EldenRingSeamlessCoopRelease#299] opened 2022-06-21 19:39 UTC
### Describe the issue in detail

when me and my friend was fighting the tree sentinel the lock on didn't work

### Steps to recreate the bug

fight the first tree sentinal and try to lock on with two people

### Version

1.2.5 (Latest)

**Comment by LukeYui** [comment] 2022-06-21 22:58
Duplicate of #59

**Closed by LukeYui** 2022-06-21 22:58 UTC
Labels: bug
