### ISSUE TITLE
[Bug]: Grace women wont stop appearing

### ISSUE THREAD

**Issue by DannyDarth** [LukeYui/EldenRingSeamlessCoopRelease#206] opened 2022-06-16 00:01 UTC
### Discord Username

DannyDarth

### Describe the issue in detail

As a coop player you sit down at the site of grace and bitch lady appears.

### Steps to recreate the bug

sit at a site in coop and the players who join you see's bitch lady.

### Version

1.2.4 (Latest)

**Comment by Mic601** [comment] 2022-06-16 02:06
Ok  I'm gonna call her the grace woman from now on.

**Comment by kagurazaki8472** [comment] 2022-06-16 14:22
The first site of grace you use when joining another player will spawn melina (but not again until you reconnect).
But after killing morgott melina will return at every site of grace to tell you go to flame giant.

Is this what your refering to?

**Comment by DannyDarth** [comment] 2022-06-16 16:14
> The first site of grace you use when joining another player will spawn melina (but not again until you reconnect). But after killing morgott melina will return at every site of grace to tell you go to flame giant.
> 
> Is this what your refering to?

yeah thats what im meaning, is there no way to stop that in coop?

**Comment by kagurazaki8472** [comment] 2022-06-16 16:55
Not that I know of,  I just want to help clairify this bug.

**Comment by LukeYui** [comment] 2022-06-16 18:24
Duplicate of #23

**Closed by LukeYui** 2022-06-16 18:24 UTC
Labels: bug
