### ISSUE TITLE
[Bug]: malenia stop moving when one of the player died

### ISSUE THREAD

**Issue by Hagure32** [LukeYui/EldenRingSeamlessCoopRelease#367] opened 2022-06-28 15:04 UTC
### Describe the issue in detail

malenia immidietly stop moving when one of the player died

### Steps to recreate the bug

fight malenia normally

### Version

1.2.5 (Latest)

**Comment by loki2236** [comment] 2022-06-28 17:08
Duplicate of #64

**Closed** 2022-07-06 21:20 UTC
Labels: bug
