### ISSUE TITLE
[Bug]: Melina and round table bugs

### ISSUE THREAD

**Issue by Forerunner187** [LukeYui/EldenRingSeamlessCoopRelease#181] opened 2022-06-14 17:55 UTC
### Discord Username

Forerunner The Interloper

### Describe the issue in detail

when resting at any grace, players joining the session will have a chance for Melina to show up as ask to take you to round table hold even if you have already been to round table. processioning through her dialog too quickly can cause you to be soft-locked in place until the host disconnects you.

Roderika will be standing in place waiting to talk to Hewg but never progresses unless you are playing without others in the session.

finger reader Enia will disappear from her room even if her door is open until you have disconnected from the session

### Steps to recreate the bug

Unsure.

### Version

1.2.4 (Latest)

**Comment by Artigas96** [comment] 2022-06-14 18:32
Me too

**Comment by LukeYui** [comment] 2022-06-14 18:40
Duplicate of #23

**Closed by LukeYui** 2022-06-14 18:40 UTC
Labels: bug
