### ISSUE TITLE
[Bug]: Calid divine tower cooperator randomly gets runes as if demigod is killed

### ISSUE THREAD

**Issue by jjburke-code** [LukeYui/EldenRingSeamlessCoopRelease#345] opened 2022-06-26 17:12 UTC
### Describe the issue in detail

In divine tower coop player (not host) gets message demi god killed and gets runes. Happened three times while fighting godskin. 

### Steps to recreate the bug

random

### Version

1.2.5 (Latest)

**Comment by loki2236** [comment] 2022-06-28 16:01
Duplicate of #56

**Closed** 2023-01-19 21:05 UTC
Labels: bug
