### ISSUE TITLE
[Bug]: Vote travel

### ISSUE THREAD

**Issue by Foxpop33** [LukeYui/EldenRingSeamlessCoopRelease#515] opened 2023-02-09 16:26 UTC
### Discord Username

Fox pop

### Describe the issue in detail

I noticed after upgrading to 1.4.3 that the first attempt on the vote travel no longer seems to recognize when one of us initiates a travel request on the first attempt. We have to wait for the first travel vote attempt to fail and then request a second vote travel attempt and the second one will successfully teleport us

### Steps to recreate the bug

When the host or the player joining tries to initiate a vote travel for the first attempt and the vote fails because it doesn't recognize that both players have voted

### Version

1.4.3 (Latest)

**Comment by LukeYui** [comment] 2023-02-09 21:29
Duplicate of #492

**Closed by LukeYui** 2023-02-09 21:29 UTC
Labels: bug
