### ISSUE TITLE
[Bug]: When a player in party die, the boss in story mode stand still.

### ISSUE THREAD

**Issue by huy232** [LukeYui/EldenRingSeamlessCoopRelease#416] opened 2022-07-09 18:15 UTC
### Describe the issue in detail

I'm using Elden Ring Reforged with Seamless Coop. But that seems isn't the case. I think the problem is with Seamless Coop since I browse the post in Nexus mod and there're a few players who have the same experience as me.

Whenever a player in a party dies, the boss will stand still, but if someone came to attack the boss, the boss will fight back, but if the player stays away, and keep their distance, the boss will continue standing still and not moving to seek for another alive player.

In my case, this problem occurs when we try to fight Godrick the Grafted.

Someone else in Nexus also has the same problem with me, so I think it's a bug from Seamless coop rather than Elden Ring Reforged mod.

### Steps to recreate the bug

First run (usually very normal and really smooth, from the moment of creating the world and other players joining in).
Go to Godrick fight.
Everything normal.
Everyone dies.
Problem starts happen in run 2, maybe 3, or 4, 5, etc.
One player in the party dies.
The boss starts standing still near the dead player.

### Version

1.3.0 (Latest)

**Comment by loki2236** [comment] 2022-07-09 19:13
Duplicate of #64

**Comment by LukeYui** [comment] 2022-07-09 19:13
Du

**Closed by LukeYui** 2022-07-09 19:13 UTC
Labels: bug
