### ISSUE TITLE
[Bug]: Melinia

### ISSUE THREAD

**Issue by Forerunner187** [LukeYui/EldenRingSeamlessCoopRelease#180] opened 2022-06-14 17:43 UTC
### Discord Username

Forerunner The Interloper

### Describe the issue in detail

when joining the host, the other players will receive the message of enemy felled or greater enemy felled and receive runes and items but no bosses have been actually been slain.

### Steps to recreate the bug

see description

### Version

1.2.4 (Latest)

**Comment by LukeYui** [comment] 2022-06-14 18:40
Duplicate of #38

**Closed by LukeYui** 2022-06-14 18:40 UTC
Labels: bug
