### ISSUE TITLE
[Bug]: cant lock on

### ISSUE THREAD

**Issue by jjburke-code** [LukeYui/EldenRingSeamlessCoopRelease#318] opened 2022-06-23 22:10 UTC
### Discord Username

Yoesph

### Describe the issue in detail

Sometimes in boss fights host cant lock on

### Steps to recreate the bug

above 

### Version

1.2.5 (Latest)

**Comment by loki2236** [comment] 2022-06-28 15:36
Duplicate of #21

**Comment by Mrqozy** [comment] 2022-07-11 07:57
> Duplicate of #21

Useless reply as always.

**Closed** 2023-01-19 21:05 UTC
Labels: bug
