### ISSUE TITLE
[Bug]: Major Boss focus dead ally location

### ISSUE THREAD

**Issue by PlayfulPosum** [LukeYui/EldenRingSeamlessCoopRelease#376] opened 2022-06-29 07:45 UTC
### Describe the issue in detail

We (me and one friend) are fighting any major boss, eg Godrick, and when one of us dies, the boss focus on where the player died. This causes the boss to stand there idle. Sometimes we could force the boss to focus on the alive player, but then would sometimes go back and stand over the spot the first player died at.

### Steps to recreate the bug

Go to Godrick fight with 2 players and have 1 of the players die. Boss will 90% of the time focus on where it killed the player if with melee.

### Version

1.2.5 (Latest)

**Comment by PowerElites** [comment] 2022-06-29 09:08
This happened to me and my friend while fighting Rennala in their 2nd phase.

**Comment by devindani** [comment] 2022-06-29 22:08
Yeah same happening to me and my friend after i conviced him to get the game and its really throwing him off.

**Comment by loki2236** [comment] 2022-06-30 16:51
Duplicate of #64

**Comment by SafetyTheFlameWolf** [comment] 2022-06-30 18:45
this happened to my brother and I when we were fighting Rennala when my brother died (he was the host) during her second phase. We tried restarting the fight by making me kill myself from Madness, however the second attempt my brother died again and the same thing happened

**Closed** 2022-07-06 21:19 UTC
Labels: bug
