### ISSUE TITLE
[Bug]: Melina tells you to burn the Erdtree at every site of grace

### ISSUE THREAD

**Issue by classyyachtmaker** [LukeYui/EldenRingSeamlessCoopRelease#234] opened 2022-06-17 14:26 UTC
### Discord Username

classyyachtmaker#6354

### Describe the issue in detail

Every time the a player other than the host rests at a site of grace Melina will tell the player to burn the Erdtree and to head to the mountain tops of the giants (after beating Morgot). This seems to override the other bug where she offers to take you to the round table. But instead of only happening once when you join/the first time you rest during the session this bug happens every time you rest. I have yet to sacrifice her to see if this will "fix" the bug. 

### Steps to recreate the bug

Rest at a sight of grace after beating Morgot and getting Melina to tell you to burn the Erdtree.
Morgot did fall through the arena during this fight but I don't think that's the reason this bug happens.

### Version

1.2.4 (Latest)

**Comment by kagurazaki8472** [comment] 2022-06-17 16:00
When I was with my friend at Castle Sol and for a few times, I rested at both sites and she did not appear.
But resting at another site away from Castle Sol, she comes back.

**Comment by LukeYui** [comment] 2022-06-18 10:39
Duplicate of #23

**Closed by LukeYui** 2022-06-18 10:39 UTC
Labels: bug
