### ISSUE TITLE
[Bug]: Ranni questline doesnt let me out while not spawning the phantoms

### ISSUE THREAD

**Issue by ihateranniquestline** [LukeYui/EldenRingSeamlessCoopRelease#126] opened 2022-06-12 17:14 UTC
### Discord Username

Milk Man#6183

### Describe the issue in detail

My friend went into the ranni tower first before i would enter and he talked through most of the dialogues. I couldnt go into the tower because of the quest forcefield. When he finished talking to them i could go in and i talked to ranni and then the phantoms you have to talk to just didnt spawn and we both couldnt fast travel. i used separation mist but the same thing happened, ranni doesnt speak, cant fast travel and phantoms dont spawn. So now we are both stuck there.

### Steps to recreate the bug

With 2 people, 1 of them should go to the tower, the other should wait while they finish talking, go into the tower, talk to ranni, enjoy.

### Version

1.2.1 (Latest)

**Comment by Nordgaren** [comment] 2022-06-12 22:56
Can you grab Elden Ring Debug Tool and set all of these flags in the misc tab? Let me know what happens. Backup your save prior, please.

https://github.com/Nordgaren/Elden-Ring-Debug-Tool/releases/tag/0.8.1

```
Enter Into Service
event flag 1034500710 1
event flag 1034500700 1
event flag 1034490701 1
event flag 1034490700 1
event flag 1034509355 1
event flag 1034509358 1
event flag 1034509357 1
event flag 1034499208 1

after blaidd 
event flag 1034509205 1
event flag 1045379208 1

after talking to sketch mcgretch at the bottom
event flag 1034509305 1
event flag 1034509306 1
event flag 1034509417 1
event flag 1034500734 1

End
event flag 1034509416 1 //This one disables the fog wall
event flag 1034500739 1
event flag 1034500733 1
event flag 1034502610 1
event flag 1034505002 1
event flag 1034505003 1
event flag 1034505004 1
event flag 1034500716 1
event flag 1034503600 1
```

**Comment by ihateranniquestline** [comment] 2022-06-13 09:30
i did all of these things and nothing happened and its either that i dont
understand what im doing or that it didnt work ant its probably the former.

2022-06-13, pr, 01:56 Nordgaren ***@***.***> rašė:

**Comment by Ambrellic** [comment] 2022-06-17 07:14
I’ve also seemed to have encountered the issue. It seems to have been caused by dying during the coop session before finishing the quest maybe. Have there been any successful ways to revert this?

**Comment by ItWasAvi** [comment] 2022-06-18 02:12
Can't revert it yet, but you still can leave from Ranni's Tower by using the debug tool --> click on grace --> warp to another site of grace that's far from that area. Any where near the Road to the Manor upwards from that direction will still to be glitched so just avoid going there at all times until it is fixed. So far that's the temporary fix for now.

**Comment by dotEXCEL** [comment] 2022-06-18 02:49
Ok here is the fix

Step 1: One player is creating a new character and joins the bugged lobby of player 2 to grab the site of grace at ranni's tower

Step2: Player one leaves the lobby and fast travels up to rannis tower

Step 3: Player 2 (bugged save) joins player 1's lobby and both talk to ranni and the spirits and ranni again

Step 4: Player 2 leaves player 1's world

Step 5: Player 2's savegame should be fixed.

Step 6: Repeat this until all savegames are fixed

Step 7: No need to thank me :D

**Comment by Zachi1027** [comment] 2022-06-18 04:19
Can confirm that this solved the issue for my friend. Thank the Elden Lords!

**Closed** 2023-01-19 21:06 UTC
Labels: bug
