### ISSUE TITLE
[Bug]: Flasks

### ISSUE THREAD

**Issue by Smolkitty666** [LukeYui/EldenRingSeamlessCoopRelease#428] opened 2022-07-14 00:34 UTC
### Discord Username

Ninelyoko7151
### Describe the issue in detail

Hello,
So I was playing the mod with my friend who had not done much in the game. I had my crimson flasks leveled up to +12 since I had been playing for a while. Me and my friend went to their first church with a sacred tear, and when we got there I was also able to pick up the sacred tear as if I had never picked that specific one up. Once I sat down at the grace, I wanted to see if I could upgrade my flask anymore since it seemed I could. I “upgraded” my flask again, and when I got out of the menu my flask was back down to +1. I have played this game for a while and am frustrated on losing all my flask progress. Now when I drink a flask it is as if I only have gotten the one. 

### Steps to recreate the bug

Have fully upgraded flask, go to friends world who doesn’t, pick up and try to upgrade your flask with their sacred tear.

### Version

1.3.0 (Latest)

**Comment by Skortchio** [comment] 2022-07-14 15:17
Version 1.2.2
Fixed a major bug which allowed guest players to upgrade their flask past +12, resetting their flask level

Also have just experienced the same bug, now left in the somewhat unappealing position of being at the Haligtree with a rank 1 flask.

**Comment by LukeYui** [comment] 2022-07-14 23:30
Duplicate of #134 

Will be fixed in the next update.

For now use the debug tool to give yourself the missing tears back.

**Closed by LukeYui** 2022-07-14 23:30 UTC
Labels: bug
