### ISSUE TITLE
[Bug]: Having to talk to Melania at site of grace

### ISSUE THREAD

**Issue by CriticalCatch** [LukeYui/EldenRingSeamlessCoopRelease#150] opened 2022-06-13 21:35 UTC
### Describe the issue in detail

This only happens when in a multiplayer session and never as the host in my experience. Once in a multiplayer session any wanderer(not host) that sits at a site of grace has to talk to Melania. It’s either about the round table or getting into the erdtree. The only time it has caused a crash in a game is when you tell Melania you want her to take you to the Round Table. This happens at every site of grace we have been too, I think the context of the conversation changes depending on where in the map you are. We were having this issue on the first patch and currently on 1.2.0.

### Steps to recreate the bug

Join a multiplayer session not as the host and sit down at any site of grace. Most recent ones it has happened at are Dragonbarrow Fork, Church of Eclipse, and Aqueduct-Facing Cliffs. 

### Version

1.2.0

**Comment by LukeYui** [comment] 2022-06-13 21:39
Duplicate of #23

**Comment by CriticalCatch** [comment] 2022-06-13 21:50
Have these been resolved? This marked as duplicate of #23, #23 marked as duplicate of #16 and #16 marked as completed. Just didn't see the fix in the patch notes. Thank you in advance.

**Comment by LukeYui** [comment] 2022-06-13 21:53
> Have these been resolved? This marked as duplicate of #23, #23 marked as duplicate of #16 and #16 marked as completed. Just didn't see the fix in the patch notes. Thank you in advance.

No it hasn't, apologies I'm not sure why these are closed. It has been reported a lot of times, I'll re-open it

**Closed** 2022-06-13 21:53 UTC
Labels: bug, duplicate

**Comment by CriticalCatch** [comment] 2022-06-13 21:59
No worries I saw a lot of the same bugs reported but, then noticed they were all closed and thought I was having a different issue. I am really enjoying this mod, thank you.
