### ISSUE TITLE
[Bug]: target lock bugged

### ISSUE THREAD

**Issue by 404streamernotfound** [LukeYui/EldenRingSeamlessCoopRelease#105] opened 2022-06-11 15:40 UTC
### Discord Username

404_streamernotfound#5904

### Describe the issue in detail

when we fight enemies on horseback the target lock bugs out and i cant target the enemies anymore until we fight new ones. this happens to each mob in the game individually so i can still lock others until the bug happens again.

### Steps to recreate the bug

1. be on horseback
2. have partners on horseback around
3. fight mobs with partners togethaa (in rykard voice)
4. use spells with target lock
5. partners are moving around the attacked enemies
6. target lock bugs
7. can only target that enemy for half a second from then on, after that the target lock stops automatically
8. can still target lock other enemies until bug happens with them as well

### Version

1.2.1 (Latest)

**Comment by LukeYui** [comment] 2022-06-11 18:02
Duplicate of #59

**Closed by LukeYui** 2022-06-11 18:02 UTC
Labels: bug
