### ISSUE TITLE
[Bug]: Flask level going to +12 when it is not supposed to

### ISSUE THREAD

**Issue by Myheartdies** [LukeYui/EldenRingSeamlessCoopRelease#267] opened 2022-06-19 12:12 UTC
### Discord Username

Neil_Yu#0939

### Describe the issue in detail

This is the exact opposite of another bug in which the flask level reset to 0. 
Instead, in one of my play session, when I join my friend as a wanderer, my flask of crimson/cerulean tears becomes +12 when it is supposed to be +5. The flask level does not revert back to the original level even after exiting the session. This never happens to me in earlier versions of this mod, and I have not done any upgrade to the flasks when I am in the current version of mod, so I would assume it happens when I join my friends session.

### Steps to recreate the bug

Have flasks that is not of max level, join another person's session as a wanderer, preferrably with bad connection (As is the case when it happens to me)

### Version

1.2.4 (Latest)

**Comment by NeoConker2k22** [comment] 2022-06-19 16:02
Out of curiosity, did you join someone whose character has progressed much further in the story than you? Like did your friend already have a +12 flask when you joined them?

I've read other bugs about people who are still early in the game joining those that have progressed much further and getting things unlocked because of this, such as the number of talisman pouches. I'm wondering if it's a similar issue here, and would likely be relevant to your bug report. Cheers.

**Comment by Myheartdies** [comment] 2022-06-19 16:06
> Out of curiosity, did you join someone whose character has progressed much further in the story than you? Like did your friend already have a +12 flask when you joined them?
> 
> I've read other bugs about people who are still early in the game joining those that have progressed much further and getting things unlocked because of this, such as the number of talisman pouches. I'm wondering if it's a similar issue here, and would likely be relevant to your bug report. Cheers.

No, me and my friend progress together and have exactly the same level for flasks before this bug happens.

**Comment by LukeYui** [comment] 2022-06-24 11:05
Duplicate of #134

**Closed by LukeYui** 2022-06-24 11:05 UTC
Labels: bug

**Comment by Yoni0040** [comment] 2022-06-24 12:06
@LukeYui this isn't a duplicate of #134 .
actually this is the exact opposite as in this case the flasks are going to +12 when they're not supposed to while in the other case they're reseting to +1
