### ISSUE TITLE
[Bug]: Rune bug {game breaking}

### ISSUE THREAD

**Issue by ItsAllFunAndGames** [LukeYui/EldenRingSeamlessCoopRelease#275] opened 2022-06-19 20:48 UTC
### Discord Username

itsallfunandgames#1868

### Describe the issue in detail

when fighting god devouring snake, when you hit the second phase, when a friend died before the second phase every thing would start to mess up, people would start to disconnected, the god devouring snake agro will solely be fixated on the dead player. 
When getting lucky and one person dies, before reaching the second phase everyone tended to disband not on their will,
while staying in the god devouring snakes second phase then join a friend , this will let you join them and every time you use a campfire you will get 50k runes.

### Steps to recreate the bug

go to volcano manor, reach the god devouring snake, have two people die before the second phase {haven't checked if it works with less players}, then if done correctly you will be by yourself. when you are join your friends again and it will cause you to get 50k runes every time you sit at a campfire.

### Version

1.2.2

**Comment by sephirothrr** [comment] 2022-06-20 01:12
Have you tried updating to the latest version?

**Comment by loki2236** [comment] 2022-06-28 16:03
Duplicate of #56

**Closed** 2023-01-19 21:05 UTC
Labels: bug
