### ISSUE TITLE
[Bug]: spawn out of world

### ISSUE THREAD

**Issue by bladexic** [LukeYui/EldenRingSeamlessCoopRelease#212] opened 2022-06-16 03:37 UTC
### Discord Username

bladexic#0305

### Describe the issue in detail

My group of 3 people total(me included) got disconnected within 3 seconds of each other, then the previously mentioned bug of a boss dying for zero reason killed godrick & then I relaunched the game as we couldn't reconnect with each other.  After loading back in my character instantly spawned under the map & fell to their death.

### Steps to recreate the bug

Location: stormhill shack
# of people 3
prior events: stated in description
steps to recreate: host have terrible internet(2mb a sec download slow) so the players joining load in faster than the map(I think as it is likely wrong)

### Version

1.2.4 (Latest)

**Comment by LukeYui** [comment] 2022-06-16 09:53
Duplicate of #186

**Closed by LukeYui** 2022-06-16 09:53 UTC
Labels: bug
