### ISSUE TITLE
[Bug] My flasks were reset upon upgrading them in my world after doing so in a friend's world

### ISSUE THREAD

**Issue by NicholasG05** [LukeYui/EldenRingSeamlessCoopRelease#280] opened 2022-06-20 02:45 UTC
### Describe the issue in detail

After I upgraded my flasks with a sacred tear at a grace, they went from being upgraded back to +1. I hadn't noticed it till my friend and I went to play again after I did so in my own world. I had been doing most of the game in his world so when I got a sacred tear in mine and upgraded, I figured it wouldn't do anything. I now am missing all the previous tears I found in the world and am stuck with +1 flasks at mid game.

### Steps to recreate the bug

I upgraded my flasks in my friend's world, returned to mine, upgraded them again with a sacred tear I found in my world, and they reset.

### Version

1.2.5 (Latest)

**Comment by LukeYui** [comment] 2022-06-24 11:06
Duplicate of #134

**Closed by LukeYui** 2022-06-24 11:06 UTC
Labels: bug
