### ISSUE TITLE
[Bug]: FLASK OF CRIMSON TEARS go to +11 to +1 instead of +12

### ISSUE THREAD

**Issue by greniesa** [LukeYui/EldenRingSeamlessCoopRelease#413] opened 2022-07-09 06:11 UTC
### Discord Username

DamianSeto (greniesa)#8752

### Describe the issue in detail

I have upgraded my flask for the level 12 in Lindel and my flask is now +1 instead of +12.

so I need 4 flask to heal myself to max health at 40 vigor,  it suck,

### Steps to recreate the bug

Acquired the last sacred tears and upgrade the FLASK OF CRIMSON TEARS to +12.

### Version

1.3.0 (Latest)

**Comment by loki2236** [comment] 2022-07-09 19:16
To fix the flask, use Nordgaren's Elden Ring Debug Tool, to give yourself more "Sacred Tears", but do it while playing solo.

**Comment by LukeYui** [comment] 2022-07-09 19:31
Duplicate of #334

**Closed by LukeYui** 2022-07-09 19:31 UTC
Labels: bug
