### ISSUE TITLE
[Bug]: game crash

### ISSUE THREAD

**Issue by 404streamernotfound** [LukeYui/EldenRingSeamlessCoopRelease#103] opened 2022-06-11 15:34 UTC
### Discord Username

404_streamernotfound#5904

### Describe the issue in detail

the game crashes everytime i am using spells on horseback in a new area (sorry the log is in german. hope it still helps)

### Steps to recreate the bug

1. enter a new area in the game on horseback
2. use a spell

### Version

1.2.1 (Latest)

### Relevant Crash log

```shell
Name der fehlerhaften Anwendung: eldenring.exe, Version: 1.4.1.0, Zeitstempel: 0x625fce14
Name des fehlerhaften Moduls: eldenring.exe, Version: 1.4.1.0, Zeitstempel: 0x625fce14
Ausnahmecode: 0xc0000005
Fehleroffset: 0x0000000000848d3d
ID des fehlerhaften Prozesses: 0x6448
Startzeit der fehlerhaften Anwendung: 0x01d87d0e8582e4e3
Pfad der fehlerhaften Anwendung: D:\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Pfad des fehlerhaften Moduls: D:\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Berichtskennung: 45425c11-1065-49e5-91a8-584df407ef91
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:
```

**Comment by LukeYui** [comment] 2022-06-11 19:08
Duplicate of #102

**Closed by LukeYui** 2022-06-11 19:08 UTC
Labels: bug
