### ISSUE TITLE
[Bug]: Melina Loop 

### ISSUE THREAD

**Issue by irobothearts** [LukeYui/EldenRingSeamlessCoopRelease#162] opened 2022-06-14 05:08 UTC
### Discord Username

Defcon 1ne

### Describe the issue in detail

While wandering in my buddies world, ever time I sit at a site of grace, it prompts one of two Melina animations. Either she offers to take me to the Round table hold, or she tells me again that I have to travel to the Mountaintops of Giants. It happens every time, and it's killing the flow of our game. It takes her like 2 minutes to talk and it happens ever time I sit to revamp my jugs etc. 

Super killing the experience. Making me not want to play. 

### Steps to recreate the bug

It happens every time I sit at a site of grace while a wanderer, but only started after we defeated Morgott. 

### Version

1.2.4 (Latest)

**Comment by LukeYui** [comment] 2022-06-14 09:35
Duplicate of #74

**Closed by LukeYui** 2022-06-14 09:35 UTC
Labels: bug
