### ISSUE TITLE
[Bug]: A friend is always there, the chest trap does not teleport, long teleportation, the wall of fog has not disappeared

### ISSUE THREAD

**Issue by Mldgetiki** [LukeYui/EldenRingSeamlessCoopRelease#388] opened 2022-07-02 17:04 UTC
### Discord Username

Mldgetiki #7523 //only message, i can send screenshots

### Describe the issue in detail

1. During a game with a friend, when we are far from each other, you can see a copy of him nearby (5-10 m). She will do the same things as a friend who is in another corner of the location, place. All sounds from hitting to taking damage are also present.
2. When trying to teleport to the Golem in the capital (the teleport is in the tower on the Weeping Peninsula, not far from the merchant), the chest teleports one player and no longer closes. They tried to use grace, but it didn't work.
3. A friend teleports to another place for a very long time when teleporting on the map. Everything would be fine if it wasn't for teleportation through blue grace or whatever it's called? The thing that remains after killing non-main bosses. She teleports me and my friend in a matter of seconds with no further problems. Is it possible to make teleportation on the map similar?
4. After killing the Ancient Hero of Zamor in Weeping Evergaol, the fog wall did not disappear, it could be passed everywhere. The problem disappeared after resting in grace.

### Steps to recreate the bug

1. You can die anywhere. You can run away for a long distance. You can teleport through a trap chest. You can try to teleport to the round table, after the dialogue with Melina.
2. Try using a chest trap. At least one definitely works. This is a chest on the Weeping Peninsula.
3. Any teleport on the map. For comparison, blue grace.
4. Killing any boss in Evergaol. Only worked with Ancient Hero of Zamor in Weeping Evergaol.

### Version

1.2.5 (Latest)

**Comment by Yoni0040** [comment] 2022-07-02 18:49
Duplicate of #2

**Comment by WysockiBartek** [comment] 2022-07-25 08:09
It might be a duplicate but numer 2 still happens. I had a similar issue with transporter chest in Dragon Burnt Ruins. The exact same resolution.

**Closed** 2023-01-19 21:04 UTC
Labels: bug
