### ISSUE TITLE
[Bug]: Flasks reset to +1 after collecting last sacred tear

### ISSUE THREAD

**Issue by BigPappyMoist** [LukeYui/EldenRingSeamlessCoopRelease#308] opened 2022-06-22 17:17 UTC
### Discord Username

BigPappyMoist#2836

### Describe the issue in detail

After collecting the last sacred tear I needed for maximum upgraded flasks, my flasks have now been reset it seems to +1 and locked there after quitting the game. They were max upgraded before I quit the game, I then quit the game, loaded back in, and now it says they are only +1. I have tried going back to previous churches to which there were no sacred tears to be found. I also cannot collect any more and I am in the consecrated snow fields now, which is an area that having only +1 flasks really sucks. Not sure what to do, especially since I really can't play the game anymore as end game content would destroy me at this rate. 

The other guys that have been playing along side me this playthrough did not seem to experience this bug, which is very odd. Not sure what to do now, but any help, response, or fix would be greatly appreciated as I really want to avoid starting over again!

### Steps to recreate the bug

*see description*

### Version

1.2.5 (Latest)

**Comment by bondarthedark** [comment] 2022-06-23 01:30
Had the exact same thing happen to me after collecting and using a Sacred Tear, went from +12 flasks to +1.

**Comment by neocult-de** [comment] 2022-06-23 22:18
In our Coop-Session we find the last tear and both tried to upgrade the Flask from +11 to +12. I as the host had no issue, but my friend got from +11 to +1 somehow. Does my consumption trigger something for him or anything?

**Comment by chrsolr** [comment] 2022-06-24 01:27
On NG+ after picking up the Sacred Tear, I had the Dot that allows you to add a new Flask. Then it when from 12 to 11.

**Comment by LukeYui** [comment] 2022-06-24 11:06
Duplicate of #134

**Closed by LukeYui** 2022-06-24 11:06 UTC
Labels: bug
