### ISSUE TITLE
[Bug]: Ranni witch Bug find 3 NPC if Host has Already done so 

### ISSUE THREAD

**Issue by LoudCrazyG** [LukeYui/EldenRingSeamlessCoopRelease#371] opened 2022-06-28 21:29 UTC
### Discord Username

LoudCrazyGs

### Describe the issue in detail

Me and a friend have an issue locking us both at Ranni rise. I had already spoken to Ranni's 3 NPC's followers. He had not. He was in my game. As a result the NPC have not spawned and we are both stuck with no NPC spawning in both saves of the game even if we separate. This means both games now cannot progress or even leave the tower and no NPC spawn in both worlds )=

### Steps to recreate the bug

have 2 saves one who has spoken to the NPCs and one that has not. have the one who has not join the person who has completed this part of the quest. get them to speak to Ranni so they are are instructed to speak to her followers. The NPI will not spawn as the host has already done this and both saves will then be locked in the tower forever!!!!!  

### Version

1.2.5 (Latest)

**Comment by Yoni0040** [comment] 2022-06-28 21:34
Duplicate of #82 
BUT in the meantime you can look at a temporary solution to help you out
this was made by @dotEXCEL 

Step 1: One player is creating a new character and joins the bugged lobby of player 2 to grab the site of grace at ranni's tower

Step2: Player one leaves the lobby and fast travels up to rannis tower

Step 3: Player 2 (bugged save) joins player 1's lobby and both talk to ranni and the spirits and ranni again

Step 4: Player 2 leaves player 1's world

Step 5: Player 2's savegame should be fixed.

Step 6: Repeat this until all savegames are fixed

**Closed** 2023-01-19 21:05 UTC
Labels: bug
