### ISSUE TITLE
[Bug]: joining a mates world some times will spam me with enemy felled and lots of runes 

### ISSUE THREAD

**Issue by madmaxx11** [LukeYui/EldenRingSeamlessCoopRelease#389] opened 2022-07-02 18:22 UTC
### Discord Username

madmaxxxx #8479

### Describe the issue in detail

some times when joining my mate I get spammed with enemy felled we are in sync and have killed all the same bosses times its the same runes as the last boss times is the same amount as a few bosses ago

### Steps to recreate the bug

not really sure

### Version

1.2.5 (Latest)

**Comment by Yoni0040** [comment] 2022-07-02 18:49
Duplicate of #56

**Closed** 2022-07-06 21:18 UTC
Labels: bug
