### ISSUE TITLE
[Bug]: Flasks Reset from +12 to +1

### ISSUE THREAD

**Issue by Somerskillz** [LukeYui/EldenRingSeamlessCoopRelease#419] opened 2022-07-10 13:30 UTC
### Discord Username

Somerskillz#0889

### Describe the issue in detail

I tried upgrading my flasks from +12 in my friends game and it reset my flasks back down to +1. Looking for a fix because this is pretty well game ending for me. 

### Steps to recreate the bug

Joined friends world. acquired sacred tear, Selected option to upgrade flask potency at site of grace. Flasks were reset to +1

### Version

1.3.0 (Latest)

**Comment by LukeYui** [comment] 2022-07-10 21:12
Please search to see if your bug has been reported already. Duplicate of #334

**Closed by LukeYui** 2022-07-10 21:12 UTC
Labels: bug
