### ISSUE TITLE
[Bug]: Game crashed upon starting. Game icon now missing.

### ISSUE THREAD

**Issue by oni102** [LukeYui/EldenRingSeamlessCoopRelease#81] opened 2022-06-11 01:18 UTC
### Describe the issue in detail

As I was booting the game using the mod shortcut, the game would crash. After crashing, the shortcut would disappear from the desktop and the game file location. As I attempted to replace the icon in the file folder, it then asked for admin permission to copy the file. After giving permission, the transfer is denied. Restarting my PC is the only way to reinstall the mod, but the same crash/error happens.

### Steps to recreate the bug

Attempt to start game. After crashing, attempt to reinstall mod.

### Version

1.2.1 (Latest)

### Relevant Crash log

```shell
Faulting application name: eldenring.exe, version: 1.4.1.0, time stamp: 0x625fce14
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x2bd748bf
Exception code: 0xc0000409
Fault offset: 0x000000000007286e
Faulting process id: 0x268c
Faulting application start time: 0x01d87c7eb097c8e0
Faulting application path: G:\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 888c9368-b8bf-43e1-af0d-c118de2a101d
Faulting package full name: 
Faulting package-relative application ID:
```

**Comment by LukeYui** [comment] 2022-06-11 13:38
Duplicate of #48

**Closed by LukeYui** 2022-06-11 13:38 UTC
Labels: bug
