### ISSUE TITLE
[Bug]: Fringefolk Hero's Grave- Chariot bug

### ISSUE THREAD

**Issue by PanTheRandomness** [LukeYui/EldenRingSeamlessCoopRelease#176] opened 2022-06-14 16:50 UTC
### Describe the issue in detail

We were playing together with my fiancé and the chariot couldn't decide which one of us to chase so it just kind of spun around, making it almost impossible to pass.

### Steps to recreate the bug

Have at least two players in different places of the Fringefolk Hero's Grave corridor

https://user-images.githubusercontent.com/107498260/173632695-7e9df832-672b-496f-b377-613c279024e7.mp4

.

### Version

1.2.4 (Latest)

**Comment by LukeYui** [comment] 2022-06-14 18:40
Duplicate of #147

**Closed by LukeYui** 2022-06-14 18:40 UTC
Labels: bug
