### ISSUE TITLE
[Bug]: Sacred tear took my flasks down to starter level

### ISSUE THREAD

**Issue by KaitieLady** [LukeYui/EldenRingSeamlessCoopRelease#207] opened 2022-06-16 00:09 UTC
### Discord Username

Missus_Drunken_Viking#6974

### Describe the issue in detail

I am on NG+ And today was wandering around, got a sacred tear and it immediately brought my flasks back to +1. I'm not sure if they can be maxed out like with the golden seeds that say there can only be a number of charges - but it did not say the sacred tear couldn't be used or anything. Same prompt "Use sacred tear to increase amount of hp/fp restored by flasks?" Yes please. Then I realised it was only restoring a fraction and I noticed below it just said +1. Unfortunately I did not take note of what +n my flasks were before it happened as it didn't even prompt me. Last time I remember looking they were at about +9.

### Steps to recreate the bug

Use a bunch of sacred tears until you notice the flask +n dropping off

### Version

1.2.4 (Latest)

**Comment by Ell3Ry** [comment] 2022-06-16 02:13
Same here. Picked up the sacred tear at Bellum Church, upgraded my flasks and noticed that they've been reset to +1. Not sure about the previous flask level though, probably +5/+6.

**Comment by pu1i** [comment] 2022-06-16 20:06
For me I was just fighting Godfrey when we got in second phase he bugged through the floor(my friend died in phase 1) after that I alt F4 and my pots are now bugged in the same way, I think that s what I did, I don t remember getting another tear and using it

**Comment by KaitieLady** [comment] 2022-06-16 22:53
I was at the first church of Marika in the mountaintops of giants btw when it happened.

**Comment by Ambrellic** [comment] 2022-06-21 03:15
I've also seemed to have gotten the bug :(

**Comment by LukeYui** [comment] 2022-06-24 11:06
Duplicate of #134

**Closed by LukeYui** 2022-06-24 11:06 UTC
Labels: bug
