### ISSUE TITLE
[Bug]: Boss goes idle during Rennala boss fight if host dies

### ISSUE THREAD

**Issue by sporefare** [LukeYui/EldenRingSeamlessCoopRelease#542] opened 2023-02-22 19:14 UTC
### Describe the issue in detail

if host dies during or before rennala 2nd phase, the wanderer joining them will not draw aggro andcan kill boss without being attacked. rennala sits in idle state

### Steps to recreate the bug

die as host while in rennala battle, leaving guest alive

### Version

1.4.5 (Latest)

**Comment by A1steaksa** [comment] 2023-03-21 21:39
This is a duplicate of https://github.com/LukeYui/EldenRingSeamlessCoopRelease/issues/64

**Closed** 2023-04-30 20:37 UTC
Labels: bug, cannot recreate
