### ISSUE TITLE
[Bug]: Dragon Agheel infinitely dying

### ISSUE THREAD

**Issue by GameFraek** [LukeYui/EldenRingSeamlessCoopRelease#313] opened 2022-06-23 10:18 UTC
### Discord Username

GameFraek#8426

### Describe the issue in detail

Since we killed dragon Agheel in Limgrave i encounter this bug occasionally when near the church of Elleh. The dragon appears to be in a death loop even though its already been defeated and shouldn't respawn. 

I believe it is this particular dragon as I remember it first happening after defeating it. You can also see that the game pops-up a message that there is a new draconic power available so its caused by a dragon and most likely this one as I do not believe we had killed any other dragon when this happened and there are no other ones close in that region. 

The bug usually occurs once or twice pretty much always after sitting by a grace, which might be specific to the church as I have not had it happen anywhere else. It can happen multiple times in a row and does not seem to go away after closing the session and opening it again with the same host. As a side effect of the death you also get runes occasionally making this an infinite runes bug although it's hard to tell how consistent it is.

Here is a link to a clip with the bug:  
https://medal.tv/games/elden-ring/clips/oPOOZ1llBmczj/d1337mxJbI9F?invite=cr-MSxwdjcsNTgwNDk4Nyw

### Steps to recreate the bug

Go to Limgrave and defeat dragon Agheel (may be required to be with 4 people).
Afterwards sit at the Church of Elleh site of Grace.
Ending the session and having the same host start it again may trigger it regardless by sitting at the grace once more.

### Version

1.2.4

### Relevant Crash log

```shell
not applicable
```

**Comment by loki2236** [comment] 2022-06-28 17:15
Duplicate of #56

**Closed** 2023-01-19 21:05 UTC
Labels: bug
