### ISSUE TITLE
[Bug]: Duplicate boss defeated messages

### ISSUE THREAD

**Issue by saber57draxus** [LukeYui/EldenRingSeamlessCoopRelease#90] opened 2022-06-11 07:40 UTC
### Discord Username

saber57draxus#7820

### Describe the issue in detail

Night Calvary bug:
When nightitime got aggroed by NC: upon switching to other world - i get "ENEMY FELLED" and 4k in runes.  

### Steps to recreate the bug

Go to Grace Site by NC
NC Aggros at night 
Use Effegy and join coop
"ENEMY FELLED" and 4k runs

### Version

1.2.1 (Latest)

**Comment by LukeYui** [comment] 2022-06-11 13:43
Duplicate of #56

**Closed by LukeYui** 2022-06-11 13:43 UTC
Labels: bug
