### ISSUE TITLE
[Bug]: Bosses stop fighting/AI break after a party member dies

### ISSUE THREAD

**Issue by Peachkid90** [LukeYui/EldenRingSeamlessCoopRelease#189] opened 2022-06-15 02:52 UTC
### Discord Username

Peachkid#9653

### Describe the issue in detail

For multiple bosses in versions 1.2.4, Malenia and Mogh especially, when my party member died, the boss just stopped fighting and stood around the corpse of the dead player who was spectating completely deaggroed on me and I was able to just range them down without them putting up any fight whatsoever

### Steps to recreate the bug

Party up, fight a boss, and have one of you die.

### Version

1.2.4 (Latest)

**Comment by LukeYui** [comment] 2022-06-15 12:07
Duplicate of #178

**Closed by LukeYui** 2022-06-15 12:07 UTC
Labels: bug
