### ISSUE TITLE
[Bug]: Infinite Runes from Red Wolf of Radagon

### ISSUE THREAD

**Issue by Nyromath** [LukeYui/EldenRingSeamlessCoopRelease#510] opened 2023-02-08 11:34 UTC
### Describe the issue in detail

My co-op partner died during the Red Wolf of Radagon fight, and I went on to defeat the boss. When I used the Site of Grace for him to respawn, he claimed to still be seeing the fog wall, not see the Site of Grace in the boss arena, and every time I sat down at that site of grace, he would get a Great Enemy Felled message and earn 14,000 runes. Closing and re-opening the world instance fixed this issue.

Also of note, during that fight he was encountering a different bug where he had the Talk to Melina option at the Site of Grace before the Red Wolf of Radagon, but no option to level up. Not sure what caused that, or if that bug had any affect on this bug.

### Steps to recreate the bug

Fight Red Wolf of Radagon with 2 players, one player dies, other player beats the boss. Player who beat the boss repeatedly sits at the Debate Parlor site of grace, earning the player who died 14,000 runes and a Great Enemy Felled prompt each time.

### Version

1.4.3 (Latest)

**Comment by LukeYui** [comment] 2023-02-09 21:33
Duplicate of #479 ..

**Closed by LukeYui** 2023-02-09 21:33 UTC
Labels: bug
