### ISSUE TITLE
[Bug] Losing ability to target in Draconic Tree Sentinel boss fight

### ISSUE THREAD

**Issue by Ed-boye** [LukeYui/EldenRingSeamlessCoopRelease#21] opened 2022-06-01 19:52 UTC
2 person coop, me and my friend (mostly my friend) would suddenly lose our ability to target the boss. I believe this was me hosting and  my friend joining me. Had to respec one of us off INT sorceries to be able to finish the fight with melee armaments that didn't require targeting like casting. Was fairly consistent in losing agility to target. Was every fight.

Not exactly sure how to reproduce but we'd both go in do the fight like we'd normally do and after some time targeting stops working. We once got it to work again by having my buddy whack the boss a few times but weren't able to reliably fix it.

**Comment by tatoyoda600** [comment] 2022-06-01 21:10
Had the exact same thing happen to a friend and me, against the regular Tree Sentinel at the start of the game though. Fought it a couple times (Maybe 10 or so), and then suddenly whenever we tried to lock on it would immediately remove the lock on.

**Comment by notshux** [comment] 2022-06-02 23:03
This happens with multiple bosses, happened to me fighting fire giant

**Comment by Arclesis420** [comment] 2022-06-05 16:05
Happened to me as well with the sentinel by the capital and the one in the starting area

**Comment by Silky322** [comment] 2022-06-09 22:27
Also an issue in Radahn, seems to happen either when a player dies or after a certain time/boss does a certain move.

**Comment by Rickus89** [comment] 2022-06-14 18:14
My brother and I have this problem as well with the Tree Sentinel and also the Night's Cavalry (Weeping Peninsula). I notice I lost the ability to target them both when they hit half health.

**Comment by Ed-boye** [comment] 2022-06-14 18:16
Oh is this still happening on latest release? @Rickus89

**Comment by Rickus89** [comment] 2022-06-14 19:08
@Ed-boye 1.2.4, so yes. We also do not use any other mods.

**Comment by Silky322** [comment] 2022-06-14 20:43
I haven't personally had the issue since 1.2.4, but one of my friends still has the lock break if he stays locked on while on horseback for too long. It will break the lock then he isn't able to restore the normal behavior even if he gets off the horse. This was specifically on Radahn for us. I did the fight on foot and had no issues even when other players in the session died or whatever moves were used.

**Comment by LukeYui** [comment] 2022-06-14 20:45
> I haven't personally had the issue since 1.2.4, but one of my friends still has the lock break if he stays locked on while on horseback for too long. It will break the lock then he isn't able to restore the normal behavior even if he gets off the horse. This was specifically on Radahn for us. I did the fight on foot and had no issues even when other players in the session died or whatever moves were used.

Did you use the rulebook to put PvP on at all during your session?

I've tried to recreate this bug but can't do it. I've tried Radahn, normal enemies, and players both on and off horseback

**Comment by Silky322** [comment] 2022-06-14 21:32
Nope, I don't think we have enabled PvP in this playthrough at all. We finally killed Radahn so I don't think I can try to reproduce there for a while but I remember also having the same issue on the tree sentinel and I think the night cavalry so I will see if we can reproduce it there and either record or narrow down the conditions.

I'll ask if he remembers the exact circumstances but from what I remember of the fight he was on horseback, locked on and casting spells, when either a player died and went to spectator mode or a certain time passed/moveset occurred that caused it. When it was happening for me it was similar conditions. Once it happens you generally can't lock at all but will occasionally get the lock on dot for a fraction of a second before it breaks again. 

Also, I was mistaken on the patch level, we killed Radahn on Sunday night so it would have been on patch 1.2.2 or earlier, not sure if that changes anything but he only mentioned the issue once and I didn't have it at all this time. I'll try to reproduce and let you know.

**Comment by Silky322** [comment] 2022-06-15 01:21
@LukeYui Alright, was able to repro a couple times. Once vs mounted enemy and once more vs non-mounted. Seems to be strictly time based and not related to being in a boss fight. Tested vs the mounted Godrick Knight above Deathtouched catacombs and some other random guy on foot around there. Also tested without anyone in my game and the issue didn't seem to occur. Videos below. I tried dismounting and the issue still persists, the lock will come up for a fraction of a second and immediately drop.

Vs Mounted Enemy:
https://youtu.be/MxQ2LSi86OU

Vs Foot enemy:
https://youtu.be/QF-1rNjxJfg

**Comment by alizorro** [comment] 2022-06-21 15:22
i hope this issues is prioritized on the list of things to fix as its making it really hard to use the mod :(

**Comment by BrienneEmyr** [comment] 2022-06-30 22:59
Commenting to not duplicate report but also having this issue. Has happened for both the host and wanderer during boss fights, lose lock on target ability, do not get it back. Version 1.2.5 (latest).

**Comment by metaface** [comment] 2022-07-01 08:42
Don't know if it helps, but one thing that I've noticed with this bug is that it doesn't seem to ever happen in dungeons/indoor areas, only ever happens on the overworld and mostly with horse mounted enemies but not exclusively to them. 1.2.5, no other mods, with three players. Horse mounted enemies lose the lock-on almost immediately.

**Comment by Bearmageddon** [comment] 2022-07-03 01:05
Also experiencing this issue. Myself and one other person. Randomly can't lock onto bosses but also affects standard enemies in our case as well. 

Assuming the session time is relevant as mentioned above, this time it started happening around an hour and a half of into this session. Also seemed to have started happening later into our session the last time it happened, too. We're both on the same network for what it's worth (wife sat at her desk across the room). 

Going to try relaunching and see if the same enemies we're currently having trouble with are still an issue with a fresh launch.

**Comment by alizorro** [comment] 2022-07-04 00:19
> Don't know if it helps, but one thing that I've noticed with this bug is that it doesn't seem to ever happen in dungeons/indoor areas, only ever happens on the overworld and mostly with horse mounted enemies but not exclusively to them. 1.2.5, no other mods, with three players. Horse mounted enemies lose the lock-on almost immediately.

Agreed, i started fighting bosses unmounted to avoid the issue and accept the fact i cant use Torrent to fight bosses :D

**Comment by Mrqozy** [comment] 2022-07-11 07:52
Why is this not fixed after 27 days! Why update the mod at all if the most basic thing which is locking on an enemy is not fixed! I hope no one donates unless this is fixed.
I regret my donation already.

**Comment by Ed-boye** [comment] 2022-07-11 17:05
Yikes, @Mrqozy.

No one said you had to donate, be upset with yourself only. If it were easy to fix I assume it would have been fixed by now. This is a place to discuss the bug not have a temper tantrum.

**Comment by Mrqozy** [comment] 2022-07-11 17:50
> Yikes, @Mrqozy.
> 
> No one said you had to donate, be upset with yourself only. If it were easy to fix I assume it would have been fixed by now. This is a place to discuss the bug not have a temper tantrum.

Yikes, @Ed-boye
No one said you had to lick the devs boots, be upset with yourself only. It is easy to fix I assume and it should have been fixed by now. This is a place to discuss the bug not lick devs boots.

**Comment by justn1** [comment] 2022-07-11 21:50
> 

If it's as easy to fix as you think it is then make a mod that fixes it yourself. As a developer, it's not easy to fix a bug when you don't know what's causing it to begin with. And no one's necessarily begging you or forcing you to donate or use this mod, instead of complaining about an unfinished mod, make your own or look for a mod that satisfies your needs.

**Comment by Mrqozy** [comment] 2022-07-12 01:15
> > > Yikes, @Mrqozy.
> > > No one said you had to donate, be upset with yourself only. If it were easy to fix I assume it would have been fixed by now. This is a place to discuss the bug not have a temper tantrum.
> > 
> > 
> > Yikes, @Ed-boye No one said you had to lick the devs boots, be upset with yourself only. It is easy to fix I assume and it should have been fixed by now. This is a place to discuss the bug not lick devs boots.
> 
> If it's as easy to fix as you think it is then make a mod that fixes it yourself. As a developer, it's not easy to fix a bug when you don't know what's causing it to begin with. And no one's necessarily begging you or forcing you to donate or use this mod, instead of complaining about an unfinished mod, make your own or look for a mod that satisfies your needs.

OK I already started making my own mod, it's 90% finished.
1 more hours and it will be finished.

My mod is called @justn1 is a pu. s_sy
Download now!

**Closed** 2023-01-19 21:06 UTC

**Comment by osyrisrblx** [comment] 2023-02-05 19:11
Hi, still running into this. Really struggling with the Radahn fight because of it.

I assume I have the latest version because I downloaded it from nexusmods.com yesterday. Haven't changed any of the PvP settings.

It seems to happen on when I lock-on to an enemy horseback. The mechanic remains broken even if I exit horseback. I am playing as host.

**Comment by achyutde13** [comment] 2023-02-11 20:17
i am encountering this bug on 1.4.3 aswell, in the tree sentinel fight lock on stops working while on horseback.
