### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by AgentK0014** [LukeYui/EldenRingSeamlessCoopRelease#523] opened 2023-02-13 04:30 UTC
### Discord Username

Agent_0014#4805

### Describe the issue in detail

Hi, 

Co op with 1 host and 1 guest. When fighting Radahn about 30-45 seconds into the fight both of us lose the ability to "lock on" to target the boss with camera or ranged attacks. When Radahn goes into second phase I believe that he is reset and we are able to lock on again for about 20 seconds but then we lose the ability to "lock on". We also summoned the NPC cooperators during the fight.

 It is hard to show exactly what happens in video or photo due to the fact that it would just look like user error. There is no issues with the performance of the game (crashes, lag etc) just the lock on not working.

### Steps to recreate the bug

Just fight Radahn with 1 host and 1 guest and summon the NPCs

### Version

1.4.3 (Latest)

**Comment by cjbottaro** [comment] 2023-02-13 21:52
I think this is a dupe of #470. We have the exact same problem, but it happens _anytime_ we're on horseback, not just the Radahn fight.

We've been working around it by dismounting before engaging any enemies... but that makes the Radahn fight really difficult... :(

**Comment by AgentK0014** [comment] 2023-02-14 02:11
we haven't had any issues on horseback but I'll test and see if that is a quick fix, Thanks

**Comment by LukeYui** [comment] 2023-02-14 18:13
Duplicate of #470. It's the same problem

**Closed by LukeYui** 2023-02-14 18:13 UTC
Labels: bug
