### ISSUE TITLE
[Bug]:  error in russian locale file

### ISSUE THREAD

**Issue by The-Vorobushek** [LukeYui/EldenRingSeamlessCoopRelease#606] opened 2023-04-02 14:31 UTC
### Describe the issue in detail

seems like ; was forgotten

### Steps to recreate the bug

in settings set language to russian

### Version

1.5.1 (Latest)

**Comment by LukeYui** [comment] 2023-04-04 14:43
Duplicate of #593

**Closed by LukeYui** 2023-04-04 14:43 UTC
Labels: bug
