### ISSUE TITLE
My Key Inventory is Full and don't let me Loot any more Key Item[Bug]: 

### ISSUE THREAD

**Issue by skame57** [LukeYui/EldenRingSeamlessCoopRelease#119] opened 2022-06-12 12:06 UTC
### Discord Username

Byaa#9474

### Describe the issue in detail

We have played 60 hours at this Mod, we are ATM at the Mountain Top of the Giant and since yesterday, my key item inventory is full.
As Host the item drop on the ground, as Client it just desapear.
I tried to make space by put some key item to the Chest and it's seems to work, but i can't get it back too, inventory full.
Same thing when i die, the Rot drop on the ground because inventory full
Look like if the inventory was limited. 
I have lastest version 1.2.1

### Steps to recreate the bug

I play with 1 frient at  version 1.2.1, we have almost finish the game. I have almost all the key items.
Also sometimes, when i die, the Rot spawn directely in the chest.

### Version

1.2.1 (Latest)

**Comment by LukeYui** [comment] 2022-06-12 16:48
Duplicate of #68

**Closed by LukeYui** 2022-06-12 16:48 UTC
Labels: bug
