### ISSUE TITLE
Melina Keeps Talking To Me Every Time I rest at a grace (she says different things at a different time of the story)[Bug]: 

### ISSUE THREAD

**Issue by HumanWeEb** [LukeYui/EldenRingSeamlessCoopRelease#77] opened 2022-06-10 23:08 UTC
### Discord Username

HumanWeeb#7260

### Describe the issue in detail

When I'm at a grace if I rest or if I die, At first she kept asking me if I wanted to go to the round table hold but after I killed Morgott she now saying another line. but then I switched to 1.2.1 (I was using other versions and it kept happening to the other versions.) And now she's asking me if I want to go to the roundtable hold, but went i went to talk to her again (by resting) seconds later she switched her dialog. EDIT: She wont talk you again when she burns the Erdertree and she dosent talk to you when you die she only talks to you when you rest 
![image_2022-06-10_191153049](https://user-images.githubusercontent.com/107282210/173161391-311d2ac2-0a4a-40b7-9831-f045b8116c80.png)
 again.

### Steps to recreate the bug

First Be in Someone's game and when you die or rest she will appear.

### Version

1.2.1 (Latest)

### Relevant Crash log

```shell
!!!!!1!!!!!

Log Name:      Application
Source:        Application Error
Date:          6/5/2022 5:08:00 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Niggers
Description:
Faulting application name: eldenring.exe, version: 1.4.1.0, time stamp: 0x625fce14
Faulting module name: ucrtbase.dll, version: 10.0.22000.1, time stamp: 0x00e78ce9
Exception code: 0xc0000409
Fault offset: 0x000000000007dd7e
Faulting process id: 0x30fc
Faulting application start time: 0x01d878d4e67591b6
Faulting application path: C:\Program Files (x86)\Steam\steamapps\common\ELDEN RING\Game\eldenring.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 0015bb95-dab3-4789-866d-809c3d4e9b49
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-05T12:08:00.4778387Z" />
    <EventRecordID>1875</EventRecordID>
    <Correlation />
    <Execution ProcessID="6620" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Niggers</Computer>
    <Security />
  </System>
  <EventData>
    <Data>eldenring.exe</Data>
    <Data>1.4.1.0</Data>
    <Data>625fce14</Data>
    <Data>ucrtbase.dll</Data>
    <Data>10.0.22000.1</Data>
    <Data>00e78ce9</Data>
    <Data>c0000409</Data>
    <Data>000000000007dd7e</Data>
    <Data>30fc</Data>
    <Data>01d878d4e67591b6</Data>
    <Data>C:\Program Files (x86)\Steam\steamapps\common\ELDEN RING\Game\eldenring.exe</Data>
    <Data>C:\WINDOWS\System32\ucrtbase.dll</Data>
    <Data>0015bb95-dab3-4789-866d-809c3d4e9b49</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

!!!!!2!!!!!


Log Name:      Application
Source:        Application Error
Date:          6/5/2022 5:07:52 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Niggers
Description:
Faulting application name: eldenring.exe, version: 1.4.1.0, time stamp: 0x625fce14
Faulting module name: ucrtbase.dll, version: 10.0.22000.1, time stamp: 0x00e78ce9
Exception code: 0xc0000409
Fault offset: 0x000000000007dd7e
Faulting process id: 0x8c4
Faulting application start time: 0x01d878d4e1da78ea
Faulting application path: C:\Program Files (x86)\Steam\steamapps\common\ELDEN RING\Game\eldenring.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 01b9e3fd-cca4-4b9d-90e0-381151276261
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-05T12:07:52.7432973Z" />
    <EventRecordID>1873</EventRecordID>
    <Correlation />
    <Execution ProcessID="5136" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Niggers</Computer>
    <Security />
  </System>
  <EventData>
    <Data>eldenring.exe</Data>
    <Data>1.4.1.0</Data>
    <Data>625fce14</Data>
    <Data>ucrtbase.dll</Data>
    <Data>10.0.22000.1</Data>
    <Data>00e78ce9</Data>
    <Data>c0000409</Data>
    <Data>000000000007dd7e</Data>
    <Data>8c4</Data>
    <Data>01d878d4e1da78ea</Data>
    <Data>C:\Program Files (x86)\Steam\steamapps\common\ELDEN RING\Game\eldenring.exe</Data>
    <Data>C:\WINDOWS\System32\ucrtbase.dll</Data>
    <Data>01b9e3fd-cca4-4b9d-90e0-381151276261</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>


!!!!!3!!!!!



Log Name:      Application
Source:        Application Error
Date:          6/5/2022 5:07:43 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Niggers
Description:
Faulting application name: eldenring.exe, version: 1.4.1.0, time stamp: 0x625fce14
Faulting module name: ucrtbase.dll, version: 10.0.22000.1, time stamp: 0x00e78ce9
Exception code: 0xc0000409
Fault offset: 0x000000000007dd7e
Faulting process id: 0x3af0
Faulting application start time: 0x01d878d4dc2d4095
Faulting application path: C:\Program Files (x86)\Steam\steamapps\common\ELDEN RING\Game\eldenring.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 4fa6f28c-4339-467e-b545-386b886815e2
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-05T12:07:43.7125595Z" />
    <EventRecordID>1871</EventRecordID>
    <Correlation />
    <Execution ProcessID="11148" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Niggers</Computer>
    <Security />
  </System>
  <EventData>
    <Data>eldenring.exe</Data>
    <Data>1.4.1.0</Data>
    <Data>625fce14</Data>
    <Data>ucrtbase.dll</Data>
    <Data>10.0.22000.1</Data>
    <Data>00e78ce9</Data>
    <Data>c0000409</Data>
    <Data>000000000007dd7e</Data>
    <Data>3af0</Data>
    <Data>01d878d4dc2d4095</Data>
    <Data>C:\Program Files (x86)\Steam\steamapps\common\ELDEN RING\Game\eldenring.exe</Data>
    <Data>C:\WINDOWS\System32\ucrtbase.dll</Data>
    <Data>4fa6f28c-4339-467e-b545-386b886815e2</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

**Comment by LukeYui** [comment] 2022-06-11 13:37
Duplicate of #61

**Closed by LukeYui** 2022-06-11 13:37 UTC
Labels: bug
