### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TopsaBOE** [LukeYui/EldenRingSeamlessCoopRelease#495] opened 2023-02-03 11:52 UTC
### Discord Username

Topsa#8008

### Describe the issue in detail

Happened in player 2's own world. Attempted to go to Roundtable hold via the grace option but got stuck in a continuous loading loop. Roundtable flashes in between the screens but never loads in properly. The issue continues even after restarting the game.

### Steps to recreate the bug

The first step would be trying to use the teleport via talking to Melina resulting in both of our games freezing. I ended up unlocking the teleport but he didn't. 
The things above were done in a previous version.

 We had been exploring the world like normal (just entering Caelid, also reached the academy) without [player 2] having unlocked Roundtable. We stopped playing in the dungeon behind the first tree guardian. In an attempt to unlock his Roundtable, he returned to his own world, teleported to Gatefront, and used the option to travel to Roundtable hold. After the Melina talk, he got stuck in an endless loading loop, changing loading screens. 

### Version

1.4.3 (Latest)

**Comment by LukeYui** [comment] 2023-02-03 18:43
The cause of the bug is fixed in 1.4.3, but players already stuck won't be saved. To restore the save file already affected:

1) Download the debug tool: https://github.com/Nordgaren/Elden-Ring-Debug-Tool/releases
2) Extract the contents of the archive.
3) Start Seamless Coop, and load up the afflicted character.
4) Open up the Debug Tool as administrator (right click => Run as administrator).
5) In the Misc tab, disable flag 11100020.
6) In the Misc tab, enable flags 105 and 115.
7) If that happened during the warp to Roundtable Hold, also enable flag 71190, which will unlock the warp there.

(Post taken from the discord server's support page)

Let me know if this solves the issue.

**Comment by kutaxoff** [comment] 2023-02-05 06:43
it fixed the same issue for me, thank you!

**Closed** 2023-02-09 21:34 UTC
Labels: bug
