### ISSUE TITLE
[Bug]: Melina Continues to tell me about Roundtable or the Erd tree when resting.

### ISSUE THREAD

**Issue by Lo-GonKaal** [LukeYui/EldenRingSeamlessCoopRelease#76] opened 2022-06-10 22:28 UTC
### Discord Username

Lo-Gon Kaal#9714

### Describe the issue in detail

Melina whenever I join as a wander always tells me to go to the roundtable hold whenever I've already been or she will tell me about burring the Erd tree even though she's already told me. This always happen when I'm playing as a wanderer or when wanderers join me when I'm the host keep in mind it never happens when I'm a host but it happens to the wanderers that join.

Another note is she only ask to go to the roundtable once when I join and rest as a wanderer, but about burning the Erd tree she will talk to me about it every time I rest as a wanderer.

### Steps to recreate the bug

Progress to when Melina ask to join roundtable, Go to roundtable, Join as wanderer, rest at site of grace, she asks again.
Progress to beat Morgott, rest at grace site, Melina talks about burning the Erd tree, join as wanderer, rest at any site of grace, Melina talks about burning the Erd tree, if you rest furthermore she will tell about burning the Erd tree every time you rest.

### Version

1.2.0

**Comment by LukeYui** [comment] 2022-06-10 22:32
Duplicate of #61

**Closed by LukeYui** 2022-06-10 22:32 UTC
Labels: bug
