### ISSUE TITLE
[Bug]: Picking up item gives a bunch of tiny great pots 

### ISSUE THREAD

**Issue by jjburke-code** [LukeYui/EldenRingSeamlessCoopRelease#229] opened 2022-06-17 03:26 UTC
### Discord Username

Yoesph

### Describe the issue in detail

friend hit y to get item on chest and got 90+ rows of tiny great pots in his inventory. Previous to this he hit Y to sit at bonfire and got one. 

### Steps to recreate the bug

2 people at southern castle opened chest

### Version

1.2.4 (Latest)

**Comment by LukeYui** [comment] 2022-06-18 11:00
Duplicate of #71

**Closed by LukeYui** 2022-06-18 11:00 UTC
Labels: bug
